CREATE TABLE IF NOT EXISTS INSTACART_ANALYTICS.ANALYTICS.DIM_PRODUCTS (
    PRODUCT_ID NUMBER,
    PRODUCT_NAME STRING,
    AISLE_ID NUMBER,
    AISLE STRING,
    DEPARTMENT_ID NUMBER,
    DEPARTMENT STRING,
    TRANSFORMED_AT TIMESTAMP_NTZ
);


CREATE TABLE IF NOT EXISTS INSTACART_ANALYTICS.ANALYTICS.DIM_USERS(
    USER_ID NUMBER,
    TOTAL_ORDERS NUMBER,
    FIRST_ORDER_NUMBER NUMBER,
    LAST_ORDER_NUMBER NUMBER,
    AVG_DAYS_SINCE_PRIOR_ORDER FLOAT,
    FIRST_ORDER_DOW NUMBER,
    MOST_COMMON_ORDER_HOUR NUMBER,
    TRANSFORMED_AT TIMESTAMP_NTZ
);


CREATE TABLE IF NOT EXISTS INSTACART_ANALYTICS.ANALYTICS.DIM_ORDERS (
    ORDER_ID NUMBER,
    USER_ID NUMBER,
    EVAL_SET STRING,
    ORDER_NUMBER NUMBER,
    ORDER_DOW NUMBER,
    ORDER_HOUR_OF_DAY NUMBER,
    DAYS_SINCE_PRIOR_ORDER FLOAT,
    IS_FIRST_ORDER BOOLEAN,
    ORDER_TIME_BUCKET STRING,
    TRANSFORMED_AT TIMESTAMP_NTZ
);