CREATE TABLE IF NOT EXISTS INSTACART_ANALYTICS.ANALYTICS.FACT_ORDER_ITEMS (
    ORDER_ID NUMBER,
    USER_ID NUMBER,
    PRODUCT_ID NUMBER,
    ADD_TO_CART_ORDER NUMBER,
    REORDERED NUMBER,
    ORDER_NUMBER NUMBER,
    ORDER_DOW NUMBER,
    ORDER_HOUR_OF_DAY NUMBER,
    DAYS_SINCE_PRIOR_ORDER FLOAT,
    EVAL_SET STRING,
    SOURCE_FILE STRING,
    TRANSFORMED_AT TIMESTAMP_NTZ
);