USE DATABASE INSTACART_ANALYTICS;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW VW_ORDER_ITEM_ANALYTICS AS
SELECT
    f.ORDER_ID,
    f.USER_ID,
    f.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.AISLE_ID,
    p.AISLE,
    p.DEPARTMENT_ID,
    p.DEPARTMENT,
    f.ADD_TO_CART_ORDER,
    f.REORDERED,
    f.ORDER_NUMBER,
    f.ORDER_DOW,
    CASE
        WHEN f.ORDER_DOW = 0 THEN 'Sunday'
        WHEN f.ORDER_DOW = 1 THEN 'Monday'
        WHEN f.ORDER_DOW = 2 THEN 'Tuesday'
        WHEN f.ORDER_DOW = 3 THEN 'Wednesday'
        WHEN f.ORDER_DOW = 4 THEN 'Thursday'
        WHEN f.ORDER_DOW = 5 THEN 'Friday'
        WHEN f.ORDER_DOW = 6 THEN 'Saturday'
        ELSE 'Unknown'
    END AS ORDER_DAY_NAME,
    f.ORDER_HOUR_OF_DAY,
    o.ORDER_TIME_BUCKET,
    f.DAYS_SINCE_PRIOR_ORDER,
    f.EVAL_SET,
    f.SOURCE_FILE,
    f.TRANSFORMED_AT
FROM FACT_ORDER_ITEMS f
LEFT JOIN DIM_PRODUCTS p
    ON f.PRODUCT_ID = p.PRODUCT_ID
LEFT JOIN DIM_ORDERS o
    ON f.ORDER_ID = o.ORDER_ID;


CREATE OR REPLACE VIEW VW_PRODUCT_PERFORMANCE AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.AISLE,
    p.DEPARTMENT,
    COUNT(*) AS TOTAL_ORDER_LINES,
    COUNT(DISTINCT f.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT f.USER_ID) AS TOTAL_USERS,
    SUM(f.REORDERED) AS TOTAL_REORDERS,
    ROUND(SUM(f.REORDERED) / NULLIF(COUNT(*), 0), 4) AS REORDER_RATE,
    ROUND(AVG(f.ADD_TO_CART_ORDER), 2) AS AVG_ADD_TO_CART_POSITION
FROM FACT_ORDER_ITEMS f
LEFT JOIN DIM_PRODUCTS p
    ON f.PRODUCT_ID = p.PRODUCT_ID
GROUP BY
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.AISLE,
    p.DEPARTMENT;


CREATE OR REPLACE VIEW VW_USER_ORDER_BEHAVIOR AS
SELECT
    u.USER_ID,
    u.TOTAL_ORDERS,
    u.AVG_DAYS_SINCE_PRIOR_ORDER,
    u.MOST_COMMON_ORDER_HOUR,
    COUNT(DISTINCT f.ORDER_ID) AS ORDERS_WITH_PRODUCTS,
    COUNT(*) AS TOTAL_ITEMS_ORDERED,
    SUM(f.REORDERED) AS TOTAL_REORDERED_ITEMS,
    ROUND(COUNT(*) / NULLIF(COUNT(DISTINCT f.ORDER_ID), 0), 2) AS AVG_BASKET_SIZE,
    ROUND(SUM(f.REORDERED) / NULLIF(COUNT(*), 0), 4) AS USER_REORDER_RATE
FROM FACT_ORDER_ITEMS f
LEFT JOIN DIM_USERS u
    ON f.USER_ID = u.USER_ID
GROUP BY
    u.USER_ID,
    u.TOTAL_ORDERS,
    u.AVG_DAYS_SINCE_PRIOR_ORDER,
    u.MOST_COMMON_ORDER_HOUR;


CREATE OR REPLACE VIEW VW_ORDER_TIME_ANALYTICS AS
SELECT
    f.ORDER_DOW,
    CASE
        WHEN f.ORDER_DOW = 0 THEN 'Sunday'
        WHEN f.ORDER_DOW = 1 THEN 'Monday'
        WHEN f.ORDER_DOW = 2 THEN 'Tuesday'
        WHEN f.ORDER_DOW = 3 THEN 'Wednesday'
        WHEN f.ORDER_DOW = 4 THEN 'Thursday'
        WHEN f.ORDER_DOW = 5 THEN 'Friday'
        WHEN f.ORDER_DOW = 6 THEN 'Saturday'
        ELSE 'Unknown'
    END AS ORDER_DAY_NAME,
    f.ORDER_HOUR_OF_DAY,
    o.ORDER_TIME_BUCKET,
    COUNT(DISTINCT f.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(*) AS TOTAL_ITEMS_ORDERED,
    COUNT(DISTINCT f.USER_ID) AS TOTAL_USERS,
    ROUND(COUNT(*) / NULLIF(COUNT(DISTINCT f.ORDER_ID), 0), 2) AS AVG_BASKET_SIZE,
    ROUND(SUM(f.REORDERED) / NULLIF(COUNT(*), 0), 4) AS REORDER_RATE
FROM FACT_ORDER_ITEMS f
LEFT JOIN DIM_ORDERS o
    ON f.ORDER_ID = o.ORDER_ID
GROUP BY
    f.ORDER_DOW,
    ORDER_DAY_NAME,
    f.ORDER_HOUR_OF_DAY,
    o.ORDER_TIME_BUCKET;