USE DATABASE INSTACART_ANALYTICS;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE FILE FORMAT CSV_FILE_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'null')
    EMPTY_FIELD_AS_NULL = TRUE;

CREATE OR REPLACE STAGE CURATED_INTERNAL_STAGE
    FILE_FORMAT = CSV_FILE_FORMAT;