name: Instacart ETL Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-etl-pipeline:
    runs-on: ubuntu-latest

    env:
      KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy kaggle

      - name: Create data folders
        run: |
          mkdir -p python_etl/data/raw
          mkdir -p python_etl/data/profiling
          mkdir -p python_etl/data/validation
          mkdir -p python_etl/data/cleaning
          mkdir -p python_etl/data/cleaned
          mkdir -p python_etl/data/curated
          mkdir -p logs

      - name: Download Instacart dataset from Kaggle
        run: |
          kaggle datasets download \
            -d yasserh/instacart-online-grocery-basket-analysis-dataset \
            -p python_etl/data/raw

          cd python_etl/data/raw
          unzip -o "*.zip"
          rm *.zip

      - name: Run master ETL pipeline
        run: |
          python -m python_etl.pipeline.run_pipeline

      - name: Upload ETL outputs
        uses: actions/upload-artifact@v4
        with:
          name: etl-output-files
          path: |
            python_etl/data/profiling/
            python_etl/data/validation/
            python_etl/data/cleaning/
            python_etl/data/cleaned/
            python_etl/data/curated/
            logs/